### PR TITLE
feat: add Samodiva and daughter models

### PR DESCRIPTION
**Pull request by adrienlucbert**
# Feature

This adds models for the Samodiva and the daughter.

image

### CODE REVIEW

**Review by jaspervonk — CHANGES_REQUESTED** [review]
Naming of the Folders should be capital, and texture is missing an s
>Daughter > texture
>Daughter > model
>Samodiva > materials
>Samodiva > model
>Samodiva > textures

**Comment by adrienlucbert** [comment]
> Naming of the Folders should be capital, and texture is missing an s
> 
> > Daughter > texture
> > Daughter > model
> > Samodiva > materials
> > Samodiva > model
> > Samodiva > textures

Remade all the namings (these and more) + removed unused resources.

**Review by jaspervonk — DISMISSED** [review]
SORRY <3

LGTM

**Review by teresa113697 — APPROVED** [review]
LGTM

**Pull request merged**
