### PR TITLE
feat: notebook popups and sounds

### PR DESCRIPTION
**Pull request by adrienlucbert**
# Feature

This adds popups when adding entries to the notebook (maps, journal, or lore). It also plays sounds when adding an entry to the notebook, when opening/closing the notebook, folding/unfolding maps, and swapping pages.

It also dynamically displays in the popup the key that needs to be pressed to open the corresponding notebook section. Pressing that key will close the popup, else it closes automatically after a delay.
The popup style was tweaked to match the designers' expectations, and the textbox size increases to fit the contained text.

image

maybe it adds an easter egg idk

### CODE REVIEW

**Review by jaspervonk — CHANGES_REQUESTED** [review]
Easter Egg :)))

Popup styling looks good! For the Text itself I would change the "lore item" part, and instead say "A new findings entry was added to the notebook". For consistency. (Same with Map Entry and Journal Entry)

The sounds for opening and closing the notebook work, but they do have a little delay on them.
This can easily be fixed by cutting the beginning part of the sound files.
(If you need help with this message me on discord)

Sadly the swapping pages sound cannot be heard? 
I've tried but couldnt find the cause of this issue.

**Comment by adrienlucbert** [comment]
> Sadly the swapping pages sound cannot be heard? I've tried but couldnt find the cause of this issue.

It was played when swapping pages (in the journal), not when changing the notebook section.
All requests were taken into account and applied.

**Review by jaspervonk — APPROVED** [review]
Pop-up text changes done, very nais!
Swapping labels now also has page flipping noise, which is good soup.
Delays being removed on all sounds makes it feel really responsive!

LGTM, force push, hand-in to marcella

**Comment by adrienlucbert** [comment]
Also fixes #60

**Pull request merged**
