### PR TITLE
feat: basic test room

### PR DESCRIPTION
**Pull request by adrienlucbert**
Very basic first test room scene, containing a non-controllable player, walls, a door, a shelf and a box.

image

Fixes [AB#82](https://dev.azure.com/DarkOceanInteractive/efeb1545-e1ba-48b4-a22c-021546c992fd/_workitems/edit/82)

### CODE REVIEW

**Comment by adrienlucbert** [comment]
@jaspervonk do you think this could be enough for a start? Or do you see anything I should add?

**Comment by jaspervonk** [comment]
I think this is good; It should have something to interact with; so the boxes are good; and a player to control;
There are 2 important notes I have:

- Its good to test interactions with smaller objects; so maybe boxes in different sizes would do; I imagen a key to be really small compared to the box in the test room; and the collision to interact should still work! Maybe have some room in between the boxes; but also have a place where a few boxes are stacked on eachother [See attached image]
- Something I cannot see but should be in the test room is a camera; since people will work with one during this sprint

Thats all! If you have done that I think its good to go
testroom boxes example

**Comment by adrienlucbert** [comment]
- Keep in mind the purpose of this room is to add up to it and scale the models the design team makes accordingly. So better keep it simple now and add things later.
- As for the camera you can free-look and edit the scene from the Unity Editor, but the scene camera is attached to the player, and not yet controllable. This will come with camera movements ([AB#139](https://dev.azure.com/DarkOceanInteractive/efeb1545-e1ba-48b4-a22c-021546c992fd/_workitems/edit/139)) and player movements.

I made smaller boxes, stacked them onto one another, and spaced them. I also added collisions and gravity to the boxes and the player. Demo below:

https://user-images.githubusercontent.com/42178413/158557831-26707280-7c1d-4f54-90fe-7d40ec80eda9.mp4

Final result:
image

**Review by jaspervonk — APPROVED** [review]
Looks great! Thanks for adding a video <3
Code is clean and no conflicts and/or inconsistencies!

**Pull request merged**
