### PR TITLE
feat: camera movement

### PR DESCRIPTION
**Pull request by andysmit1**
**Added features**

1. The camera is able to be focus on an object with the player only being able to move forward. 
2. The camera is able to "float" towards an point of interest. (and return after x seconds).
3. All movement-controls of the player can be disabled (and enabled after x seconds).

**Extra context**
All methods are able to be activated by trigger.
To disable a "camera state". a second trigger can be placed which runs the same method.

### CODE REVIEW

**Comment by jaspervonk** [comment]
Looks good, but there are some tweaks that I think need to be made
**My observations:**
1. Bug that if you keep running into the same lock triggerbox, itll randomly lock you everytime move
2. Currently, whenever you trigger a camera cutscene, your "character" aka, the camera, get's moved to the spot in the scene to focus on an object
3. The player has no visual feedback when they are locked/focused on an object

**Suggested Changes:**
1. Destroy the Trigger when it is triggered. So it cannot happen again. This is also a meant to be behavior, that they can only trigger 1 time. This in theory, should also fix the bug mentioned before
2. A: Currently the camera cutscene trigger moves the camera object, while originally it is meant to only move the rotation/focus of the camera to an object in the scene. So the camera/player is still in the same position, but the camera force-focusses on an object. Here is a visual reference: https://youtu.be/RiPpsP5hCsc?t=23059 
they pull the lever and the camera force focusses on the machine. They are still able to move here,  which be a nice extra to have, to be able to enable/disable player movement on the TriggerCameraCutscene if there is time for it.
2. B: The "Triggers" gameobjects, should have a parameter where you can attach the object to focus on, so it is easier to apply the tech, instead of having a camera in the scene beforehand. (AKA, not to use the Focus Camera to switch between, since only the camera rotation of the player should move)
3. To improve clarity for the player, make some black boxes around the screen for a more cinematic view, while also letting the player know this is meant to be: Here is a reference (The boxes here are a bit transparant, solid black boxes would be fine too)
image

**Comment by adrienlucbert** [comment]
Reacting to Jasper's comment:
1. I would argue that that's not an issue, as the triggers are here just for the demo, the methods to lock camera and stuff should remain generic, and not have the responsibility to destroy a trigger or anything. That's the responsibility of the person setting up the trigger method for the camera lock. (side note, that could be added on the trigger box prefab, as a checkbox "Destroy on trigger" or something)

**Comment by jaspervonk** [comment]
Adding onto Adrien's comment:

1. To add the 1 time use only behaviour, I think we should, as you suggested, add a script that destroys a gameobject, and apply that on the triggerbox after the camera focus functions are called

**Comment by andysmit1** [comment]
I did not include the black bar implementation, It's weird and confusing for the player. You'd expect an actual cutscene when black bars show up. Instead it's just the character looking around. It's also a bit strange from an immersion standpoint. The character (you play!) is looking around, why would black bars show up in his eyesight? it makes no sense.

**Comment by adrienlucbert** [comment]
Applied some feedback from Jasper, and the review:
- simplified scripts usage (can be used through the CameraManager and InputManager singletons)
- add possibility to provide a look-at target and blend time in the event trigger
- calculate the blending time according to the angle between the camera and the target
- leave player camera looking at the target after look-at transition (instead of moving back to initial camera position)
- movement and camera lock scripts affect input providers instead of using a different action map (would have needed extra maintenance)

ezgif-5-ae62f9abdd

**Comment by adrienlucbert** [comment]
Ready to be merged, awaiting new review from @jaspervonk.

**Review by jaspervonk — APPROVED** [review]
All feedback has been applied
Works as intended from design stand-point
Code naming has also been adjusted, nice LGTM

**Pull request merged**
